name: ruso_chat
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.1
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.16
  rflutter_alert: ^2.0.4
  geolocator: ^8.2.1
  modal_progress_hud_nsn: ^0.2.1
  http: ^0.13.4
  lottie: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

 
  uses-material-design: true

   
  assets:
     - images/
  fonts:
    - family: Pacifico
      fonts:
      - asset: fonts/Pacifico-Regular.ttf
    - family: Source Sans Pro
      fonts:
      - asset: fonts/SourceSansPro-Regular.ttf
   
     

  
